### ISSUE TITLE
React Native ACP Assurance extension displays the wrong latest version in the Previous SDK versions page

### ISSUE THREAD

**Issue by cacheung** [AdobeDocs/acp-mobile-sdkdocs#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://developer.adobe.com/client-sdks/previous-versions/documentation/sdk-versions/#react-native,

### What's wrong with the content?

In Previous SDK version page,
https://developer.adobe.com/client-sdks/previous-versions/documentation/sdk-versions/#react-native, the latest Assurance react native version shows v4.0.0. 

![assuranceACPReactNative](https://user-images.githubusercontent.com/29806547/228963138-2b2f1d16-ff18-4518-ad75-7eadcd16abf1.png)

### What changes do you propose?

 It should display the Assurance react native version compatible with the ACP.

**Comment by yangyansong-adbe** [comment]
https://github.com/AdobeDocs/acp-mobile-sdkdocs/pull/59
