### ISSUE TITLE
Broken link in sdk comparision about lifecycle

### ISSUE THREAD

**Issue by morritza** [AdobeDocs/acp-mobile-sdkdocs#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The link is broken for the reference to platform sdk lifecycle implementation

Yes. See [Manual Lifecycle Implementation](https://developer.adobe.com/client-sdks/previous-versions/documentation/upgrade-platform-sdks/comparison/lifecycle.md)
 should guide to: https://developer.adobe.com/client-sdks/documentation/mobile-core/lifecycle/ ?

### Actual behavior

"Yes. See [Manual Lifecycle Implementation](https://developer.adobe.com/client-sdks/previous-versions/documentation/upgrade-platform-sdks/comparison/lifecycle.md)"
leads to a 404

### Steps to reproduce

Go to https://developer.adobe.com/client-sdks/previous-versions/documentation/upgrade-platform-sdks/comparison/#core-functionality and click "Yes. See [Manual Lifecycle Implementation]"

### Environment

- Browser: Chrome
- OS: Mac

**Comment by swarna04** [comment]
@morritza The broken Lifecycle link has been fixed. Thanks for the feedback.
